server:
  port: 8090

management:
  security:
    enabled: false    

promotion: action

spring:
  application:
    name: awesome-media-backend
  datasource:
    platform: h2
    initialize: true
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mediadb;
    username: sa
    password: null
  h2:
    console:
      enabled: true

name: kimkangil

eureka: 
  instance:
    instance-id: localhost:${server.port}
    hostname: localhost
    lease-renewal-interval-in-seconds: 10
    lease-expiration-duration-in-seconds: 10
  client:
    region: default
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
